CREATE TABLE if not exists `{project}.{dataset}.cl_location_monthly_inforce`
(
    InforceDateKey	INT64,,
    InforceDate	    DATE,
    AccountNumber	STRING,
    PolicyNumber	STRING,
    PolicyNumber_LocationNumber	STRING,
    PolicyOrigEffDate	    INT64,
    PolicyEffectiveDate	    INT64,
    PolicyExpirationDate	INT64,
    AccountSegment	    STRING,
    ProductLineCode     STRING,
    LOB_Code	        STRING,
    NewRenewal      	STRING,
    AutoPayIndicator	BOOL,
    PaymentMethod	    STRING,
    Producer_Service_Agency_Master_Code	    STRING,
    Producer_Service_Agency_Master_Name	    STRING,
    Producer_Service_Agency_SubCode	STRING,
    Producer_Service_Agency_Code	STRING,
    Producer_Service_Agency_Name	STRING,
    Location_State_Code	    STRING,
    Location_Country_Code	STRING,
    Location_City	        STRING,
    Location_County	        STRING,
    LocationPostalCode	    STRING,
    LocationNumber	        INT64,
    Primary_Insured_State	STRING,
    Primary_Insured_Country	STRING,
    LocationJB_JS_Premium	NUMERIC,
    LocationBOP_Premium     NUMERIC,
    LocationUMB_Premium     NUMERIC,
    LocationPremiumInforce  NUMERIC,
    bq_load_date    DATE
    )
PARTITION BY InforceDate;