CREATE TABLE if not exists `{project}.{dataset}.t_{table}`
(
  WMO STRING,
  WBAN STRING,
  ICAO STRING,
  SRC_ID STRING,
  STATION_NAME STRING,
  STATE STRING,
  LAT STRING,
  LONG STRING,
  ALT STRING,
  DATE DATE,
  MONTH STRING,
  YEAR INT64,
  TMAX_DATATYPE STRING,
  DAILY_MAX_TEMP STRING,
  TMIN_DATATYPE STRING,
  DAILY_MIN_TEMP STRING,
  RAIN_DATATYPE STRING,
  DAILY_RAIN STRING,
  SNOW_DATATYPE STRING,
  DAILY_SNOWFALL STRING,
  WIND_AVE_DATATYPE STRING,
  DAILY_WIND_AVE STRING,
  DAILY_WIND_MAX_GUS_DATATYPE STRING,
  DAILY_WIND_MAX_GUST STRING
)
PARTITION BY RANGE_BUCKET(YEAR, GENERATE_ARRAY(1900, 2100, 1));